FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y httpd 
RUN mkdir /tmp/docker
RUN touch /tmp/docker/test.txt

EXPOSE 80
CMD /usr/sbin/httpd -g "daemon off;"



==============================================
